export enum Configuration {
    PORT = 'PORT',
    BUCKET_NAME='BUCKET_NAME',
    AWS_ACCESS_KEY='AWS_ACCESS_KEY',
    AWS_SECRET_ACCESS_KEY='AWS_SECRET_ACCESS_KEY',
    S3_ENDPOINT='S3_ENDPOINT',
    BUCKED_ENDPOINT='BUCKED_ENDPOINT'
}